pipeline {
        agent {
                label 'docker'
              }
        tools {
                maven 'mavvu'
              }
    stages {
        stage('Build') {
            steps {
    
                sh 'mvn clean install -f pom.xml'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
