pipeline {
        agent {
                label 'docker'
              }
        tools {
                maven 'mavvu'
              }
    stages {
        stage('run-parallel-branches') {
           steps {
               parallel(
                   a: {
                       sh 'mvn clean install -f pom.xml'
                      },
                   b: {
                       echo "parellel stage works !"
                      }
                      )
                 }
        }       
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                    sh './jenkins/scripts/deliver.sh'     
            } 
        }    
    }
}
